# Generated by Django 2.2.2 on 2019-06-13 20:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_participacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parti', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('puesto', models.CharField(max_length=60)),
                ('empresa', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=70)),
                ('telefono', models.IntegerField(max_length=12)),
                ('mensaje', models.CharField(blank=True, max_length=60)),
                ('horaRegistro', models.DateTimeField(default=django.utils.timezone.now)),
                ('intereses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Interes')),
                ('tipo_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.Tipo_participacion')),
            ],
        ),
    ]
