# Generated by Django 2.2.2 on 2019-06-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20190613_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_part',
        ),
    ]
