# Generated by Django 2.2.2 on 2019-06-14 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_remove_usuario_tipo_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='intereses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.Interes'),
        ),
    ]
