# Generated by Django 2.2.2 on 2019-06-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_auto_20190614_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='intereses',
        ),
        migrations.AddField(
            model_name='usuario',
            name='intereses',
            field=models.ManyToManyField(to='evento.Interes'),
        ),
    ]
