# Generated by Django 2.2.2 on 2019-06-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_auto_20190614_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='participacion',
            field=models.ManyToManyField(to='evento.Tipo_participacion'),
        ),
    ]
