# Generated by Django 2.2.2 on 2019-06-21 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_usuario_participacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='participacion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='participacion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='evento.Tipo_participacion'),
            preserve_default=False,
        ),
    ]
