# Generated by Django 2.2.2 on 2019-06-21 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_auto_20190621_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='participacion',
            new_name='part',
        ),
    ]
