# Generated by Django 2.2.2 on 2019-07-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0009_auto_20190621_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='asistencia',
            field=models.BooleanField(default=False),
        ),
    ]
