# Generated by Django 2.2.2 on 2019-08-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0010_usuario_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_expositor', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='mensaje',
        ),
    ]
