# Generated by Django 2.2.2 on 2019-08-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0011_auto_20190802_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='appellidoM',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='appellidoP',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
