# Generated by Django 2.2.2 on 2019-08-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0013_dns'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='resumen',
            field=models.CharField(default=0, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='titulo_exposicion',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
