# Generated by Django 2.2.2 on 2019-08-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0014_auto_20190811_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='logo',
            field=models.ImageField(default=0, upload_to='logos'),
            preserve_default=False,
        ),
    ]
