# Generated by Django 2.2.2 on 2019-08-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0015_publicaciones_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoresRelevantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_expositor', models.CharField(max_length=100)),
                ('fotografia', models.ImageField(upload_to='autores')),
            ],
        ),
    ]
