# Generated by Django 2.2.2 on 2019-08-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0016_autoresrelevantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=100)),
            ],
        ),
    ]
