# Generated by Django 2.1.5 on 2019-08-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0017_textoadicional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saludo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=1000)),
            ],
        ),
    ]
