# Generated by Django 2.2.2 on 2019-09-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0018_saludo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='appellidoM',
        ),
    ]
