# Generated by Django 2.2.2 on 2019-10-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0019_remove_usuario_appellidom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina_comprador', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos')),
                ('comprador_nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=900)),
            ],
        ),
    ]
