# Generated by Django 2.2.2 on 2019-10-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0020_comprador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
            ],
        ),
    ]
